# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 17:52
from __future__ import unicode_literals

from django.db import migrations


def install_login_service(apps, schema_director):
    Service = apps.get_model('service', 'Service')
    Service.objects.get_or_create(name='login', defaults={'url': 'https://login.presencetest.com'})


class Migration(migrations.Migration):

    dependencies = [
        ('plauth', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(install_login_service),
    ]
